CREATE TABLE GEEK
(
    idGeek INT PRIMARY KEY NOT NULL,
    nom VARCHAR(100),
    prenom VARCHAR(100),
    email VARCHAR(255),
    ville VARCHAR(255),
    sexe VARCHAR(1)
)

CREATE TABLE CENTREINTERET
(
	idCentreInteret INT PRIMARY KEY NOT NULL,
	libelle VARCHAR(255)
)

CREATE TABLE CONSULTATION
(
    idConsultation INT PRIMARY KEY NOT NULL,
    compteur INT,
	adresseIP VARCHAR(15),
	idGeek INT
)

CREATE TABLE LIEN_GEEK_CI
(
	idGeek INT NOT NULL,
	idCentreInteret INT NOT NULL,
	CONSTRAINT geek_centreInteret PRIMARY KEY(idGeek,idCentreInteret)
)

/*LIEN_GEEK_CI*/
ALTER TABLE LIEN_GEEK_CI ADD CONSTRAINT FK_LienGeekCiGeek
FOREIGN KEY (idGeek) REFERENCES GEEK(idGeek);
ALTER TABLE LIEN_GEEK_CI ADD CONSTRAINT FK_LienGeekCiCentreInteret
FOREIGN KEY (idCentreInteret) REFERENCES CENTREINTERET(idCentreInteret);
/*CONSULTATION*/
ALTER TABLE CONSULTATION ADD CONSTRAINT FK_ConsultationGeek
FOREIGN KEY (idGeek) REFERENCES GEEK(idGeek)